name: CI
on:
  push:
    branches:
      - master
      - main
    tags:
      - '*'
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java: [ '8' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JVM
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'sbt'

      - run: sbt -v +scripted
